name: Release
run-name: Build & Release
on:
  push:
    branches:
      - 'release-**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - uses: pnpm/action-setup@v3
        name: Setup pnpm
        with:
          version: 8

      - name: Install deppendencies
        run: pnpm install

      - name: Build
        run: pnpm run build

      # I may need to add the dockerfile so it can build the image after
      - name: Push artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-dist
          path: |
            .next/standalone
            Dockerfile

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get artifact
        uses: actions/download-artifact@v4
        with:
          name: frontend-dist

      - name: Create out
        run: mkdir out

      - name: Move to out
        run: mv $(ls | grep -v out) out

      - name: Zip dist
        run: tar -czvf app.tar.gz ./out

      - name: Remove out
        run: rm -rf out

      - name: SCP artifact
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ vars.SSH_HOST }}
          username: ${{ vars.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: app.tar.gz
          target: /home/ubuntu/services/frontend/

      - name: Connect to server
        uses: appleboy/ssh-action@v1.0.3
        env:
          GOAUTH_KEY: ${{ vars.NEXT_PUBLIC_GOAUTH }}
          DOCKER_IMAGE: minesweeper:front
          BACKEND_DOCKER_IMAGE: minesweeper:api
        with:
          host: ${{ vars.SSH_HOST }}
          username: ${{ vars.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          envs: GOAUTH_KEY,DOCKER_IMAGE,BACKEND_DOCKER_IMAGE
          script: |
            docker stop $(docker ps -aq -f "ancestor=$DOCKER_IMAGE")
            docker rm $(docker ps -aq -f "ancestor=$DOCKER_IMAGE") 2> /dev/null & docker rmi $(docker images -aq -f "reference=$DOCKER_IMAGE") 2> /dev/null
            cd /home/ubuntu/services/frontend
            tar -xzvf app.tar.gz
            mv out/* .
            docker build -t $DOCKER_IMAGE .
            docker run -d -p 3000:3000 -e API_URL=http://$(docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $(docker ps -aq -f "ancestor=$BACKEND_DOCKER_IMAGE")):3001 -e NEXT_PUBLIC_GOAUTH=$GOAUTH_KEY $DOCKER_IMAGE
          # rm -rf *
